instrument:
  dump_rate: 0.5
noise_diode:
  pattern: all
  on_fraction: -1.0
  cycle_len: 0.1
observation_loop:
  - LST: 0.0-23.9
    target_list:
      - name=1934-638, radec=19:39:25.03 -63:42:45.63, tags=target, duration=180.0, type=drift_scan
      - name=0408-65, radec=04:08:20.38 -65:45:09.1, tags=target, duration=180.0, type=drift_scan
