instrument: c856M4k
observation_loop:
  - LST: 0-23
    target_list:
      - name=, radec=0 -90, tags=target, duration=10.0
      - name=, azel=10 50, tags=target, duration=10.0
      - name=, gal=-10 40, tags=target, duration=10.0
    calibration_standards:
